### ISSUE TITLE
License

### ISSUE THREAD

**Issue by comradekingu** [hovancik/hovancik.github.io#83]
Can you put a license on this. AGPLv3+ or something :)

**Comment by hovancik** [comment]
Yeah I am missing that. 

I wonder, are you asking because of content or code? Not really sure what are good licenses for such a usecases

**Comment by comradekingu** [comment]
Asking because it is on Weblate, and I want to contribute to it :)
AGPLv3+ has the network protection clause, meaning distribution over a network also constitutes distribution.

**Comment by hovancik** [comment]
Ah, I see :) Main Stretchly's repo is here: https://github.com/hovancik/stretchly

Could you please wait with Weblate? I am only testing it now so not sure if I end up using it

**Comment by hovancik** [comment]
My project got approved by Weblate :)
