### ISSUE TITLE
Delay break

### ISSUE THREAD

**Issue by et8188** [hovancik/hovancik.github.io#87]
It would be fantastic if the option to delay the break rather than skip was included. I often skip as it comes up in the middle of something important and then forget to go back to it.

**Comment by hovancik** [comment]
Hi @et8188 , main repo for Stretchly is here: https://github.com/hovancik/stretchly

But with your question, the system works like this: 
- by default, for first 30 % of break, you can Postpone the break (2 minutes for Mini, 5 minutes for Long)
- then you can only skip the break
- you can Postpone break once

In Preferences file, you can change those defaults (https://github.com/hovancik/stretchly#editing-postpone-functionality-): 
- how many times do you want to Postpone
- for how long do you want to Postpone
- for how much percentage duration of break do you want to allow this

Hope this helps :)

**Comment by et8188** [comment]
Thank you for your reply - but how do I access the preferences on the
program?

Chris Townsend
Managing Director
*I am currently working reduced hours Mon-Thur approx. 8.30-1.30*
The Redwoods Caring Foundation
6 Lasswade Road
Edinburgh
EH16 6RZ
0131 672 2999 / 07928 178874
chris@redwoods.org.uk

CHECK OUT OUR NEW WEBSITE: WWW.REDWOODS.ORG.UK



**********************************************************************
Email Disclaimer – The Redwoods Caring Foundation
This email and any files transmitted with it are confidential and
intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify
the sender and ensure it is deleted and not read copied or disclosed
to anyone else. It is your responsibility to scan this email and any
attachments for computer viruses or other defects.
The Redwoods Caring Foundation does not accept liability for any loss or
damage which may
result from this email or any files attached. Email is not secure and
can be intercepted, corrupted or amended without the knowledge of the
sender. The Redwoods Caring Foundation does not accept liability for errors
or
omissions arising as a result of interrupted or defective transmission.
**********************************************************************

**Comment by hovancik** [comment]
This is accessible via preferences file: https://github.com/hovancik/stretchly#advanced-preferences
